//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

AdaptitService_copyLesson_args = function(args) {
  this.authToken = null;
  this.lessonCode = null;
  if (args) {
    if (args.authToken !== undefined) {
      this.authToken = args.authToken;
    }
    if (args.lessonCode !== undefined) {
      this.lessonCode = args.lessonCode;
    }
  }
};
AdaptitService_copyLesson_args.prototype = {};
AdaptitService_copyLesson_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.authToken = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.lessonCode = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AdaptitService_copyLesson_args.prototype.write = function(output) {
  output.writeStructBegin('AdaptitService_copyLesson_args');
  if (this.authToken) {
    output.writeFieldBegin('authToken', Thrift.Type.STRING, 1);
    output.writeString(this.authToken);
    output.writeFieldEnd();
  }
  if (this.lessonCode) {
    output.writeFieldBegin('lessonCode', Thrift.Type.STRING, 2);
    output.writeString(this.lessonCode);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AdaptitService_copyLesson_result = function(args) {
  this.success = null;
  this.aelpEx = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.aelpEx !== undefined) {
      this.aelpEx = args.aelpEx;
    }
  }
};
AdaptitService_copyLesson_result.prototype = {};
AdaptitService_copyLesson_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.aelpEx = new AELPException();
        this.aelpEx.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AdaptitService_copyLesson_result.prototype.write = function(output) {
  output.writeStructBegin('AdaptitService_copyLesson_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  if (this.aelpEx) {
    output.writeFieldBegin('aelpEx', Thrift.Type.STRUCT, 1);
    this.aelpEx.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AdaptitServiceClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
AdaptitServiceClient.prototype = {};
AdaptitServiceClient.prototype.copyLesson = function(authToken, lessonCode, callback) {
  if (callback === undefined) {
    this.send_copyLesson(authToken, lessonCode);
    return this.recv_copyLesson();
  } else {
    var postData = this.send_copyLesson(authToken, lessonCode, true);
    return this.output.getTransport()
      .jqRequest(this, postData, arguments, this.recv_copyLesson);
  }
};

AdaptitServiceClient.prototype.send_copyLesson = function(authToken, lessonCode, callback) {
  this.output.writeMessageBegin('copyLesson', Thrift.MessageType.CALL, this.seqid);
  var args = new AdaptitService_copyLesson_args();
  args.authToken = authToken;
  args.lessonCode = lessonCode;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush(callback);
};

AdaptitServiceClient.prototype.recv_copyLesson = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new AdaptitService_copyLesson_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.aelpEx) {
    throw result.aelpEx;
  }
  if (null !== result.success) {
    return result.success;
  }
  throw 'copyLesson failed: unknown result';
};
