//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

UtilService_createLatexEquation_args = function(args) {
  this.equation = null;
  if (args) {
    if (args.equation !== undefined) {
      this.equation = args.equation;
    }
  }
};
UtilService_createLatexEquation_args.prototype = {};
UtilService_createLatexEquation_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.equation = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UtilService_createLatexEquation_args.prototype.write = function(output) {
  output.writeStructBegin('UtilService_createLatexEquation_args');
  if (this.equation) {
    output.writeFieldBegin('equation', Thrift.Type.STRING, 1);
    output.writeString(this.equation);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

UtilService_createLatexEquation_result = function(args) {
  this.success = null;
  this.aelpEx = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.aelpEx !== undefined) {
      this.aelpEx = args.aelpEx;
    }
  }
};
UtilService_createLatexEquation_result.prototype = {};
UtilService_createLatexEquation_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.aelpEx = new AELPException();
        this.aelpEx.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UtilService_createLatexEquation_result.prototype.write = function(output) {
  output.writeStructBegin('UtilService_createLatexEquation_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  if (this.aelpEx) {
    output.writeFieldBegin('aelpEx', Thrift.Type.STRUCT, 1);
    this.aelpEx.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

UtilServiceClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
UtilServiceClient.prototype = {};
UtilServiceClient.prototype.createLatexEquation = function(equation, callback) {
  if (callback === undefined) {
    this.send_createLatexEquation(equation);
    return this.recv_createLatexEquation();
  } else {
    var postData = this.send_createLatexEquation(equation, true);
    return this.output.getTransport()
      .jqRequest(this, postData, arguments, this.recv_createLatexEquation);
  }
};

UtilServiceClient.prototype.send_createLatexEquation = function(equation, callback) {
  this.output.writeMessageBegin('createLatexEquation', Thrift.MessageType.CALL, this.seqid);
  var args = new UtilService_createLatexEquation_args();
  args.equation = equation;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush(callback);
};

UtilServiceClient.prototype.recv_createLatexEquation = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new UtilService_createLatexEquation_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.aelpEx) {
    throw result.aelpEx;
  }
  if (null !== result.success) {
    return result.success;
  }
  throw 'createLatexEquation failed: unknown result';
};
